import java.awt.Cursor;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import net.iharder.jpushbullet2.PushbulletException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shazrin
 */
public class LoginForm extends javax.swing.JFrame {
    
    public static boolean displayed = true;
    
    Icon setText = new ImageIcon(getClass().getResource("set_text.png"));
    
    /**
     * Creates new form LoginAPI
     */
    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    int X;
    int Y;
    int cX;
    int cY;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invalidText = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        setAPIkeytext = new javax.swing.JLabel();
        APITextField = new javax.swing.JTextField();
        setAPIbutton = new javax.swing.JButton();
        framebar = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invalidText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        invalidText.setForeground(new java.awt.Color(255, 0, 51));
        invalidText.setText("  ");
        getContentPane().add(invalidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, 20));

        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 4, 15, 15));

        setAPIkeytext.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        setAPIkeytext.setText("Enter your API key:");
        getContentPane().add(setAPIkeytext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        getContentPane().add(APITextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 400, -1));

        setAPIbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/set.png"))); // NOI18N
        setAPIbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setAPIbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                setAPIbuttonMouseEntered(evt);
            }
        });
        getContentPane().add(setAPIbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 60, 25));

        framebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framebarMouseDragged(evt);
            }
        });
        framebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framebarMousePressed(evt);
            }
        });
        getContentPane().add(framebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pushy_bg_1.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered
        closeButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void framebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framebarMouseDragged
        X = evt.getXOnScreen();
        Y = evt.getYOnScreen();
        this.setLocation(X-cX, Y-cY);
    }//GEN-LAST:event_framebarMouseDragged

    private void framebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framebarMousePressed
        cX = evt.getX();
        cY = evt.getY();
    }//GEN-LAST:event_framebarMousePressed

    private void setAPIbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setAPIbuttonMouseEntered
        setAPIbutton.setRolloverIcon(setText);
    }//GEN-LAST:event_setAPIbuttonMouseEntered

    private void setAPIbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setAPIbuttonMouseClicked
        String APIKeys = APITextField.getText();
        PushBulletService.setAPI(APIKeys);
        try{
            PushBulletService.setDevicesList();
            displayed = false;
            setVisible(false);
        }catch(PushbulletException e){
            invalidText.setText("INVALID API KEY");
            APITextField.setText("");
        }
    }//GEN-LAST:event_setAPIbuttonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField APITextField;
    private javax.swing.JLabel background;
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel framebar;
    private javax.swing.JLabel invalidText;
    private javax.swing.JButton setAPIbutton;
    private javax.swing.JLabel setAPIkeytext;
    // End of variables declaration//GEN-END:variables
}
