import java.awt.Cursor;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class MainScreenForm extends javax.swing.JFrame {
    
    Icon resetText = new ImageIcon(getClass().getResource("reset_text.png"));
    Icon sendText = new ImageIcon(getClass().getResource("send_text.png"));
    
    int X;
    int Y;
    int cX;
    int cY;
    
    public MainScreenForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTextField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        bodyLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bodyTextArea = new javax.swing.JTextArea();
        sendToLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deviceList = new javax.swing.JList<>(PushBulletService.getDevicesList());
        sendButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        closeLabel = new javax.swing.JLabel();
        framebar = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pushy");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleTextField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        getContentPane().add(titleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 400, -1));

        titleLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        titleLabel.setText("Title:");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        bodyLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bodyLabel.setText("Body:");
        getContentPane().add(bodyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        bodyTextArea.setColumns(20);
        bodyTextArea.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bodyTextArea.setRows(5);
        jScrollPane1.setViewportView(bodyTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 400, 170));

        sendToLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        sendToLabel.setText("Send to:");
        getContentPane().add(sendToLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        deviceList.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(deviceList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 400, 80));

        sendButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/send.png"))); // NOI18N
        sendButton.setPreferredSize(new java.awt.Dimension(60, 25));
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendButtonMouseEntered(evt);
            }
        });
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        resetButton.setPreferredSize(new java.awt.Dimension(60, 25));
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetButtonMouseEntered(evt);
            }
        });
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        closeLabel.setMaximumSize(new java.awt.Dimension(12, 14));
        closeLabel.setMinimumSize(new java.awt.Dimension(12, 14));
        closeLabel.setPreferredSize(new java.awt.Dimension(15, 12));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLabelMouseEntered(evt);
            }
        });
        getContentPane().add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 5, -1, -1));

        framebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framebarMouseDragged(evt);
            }
        });
        framebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framebarMousePressed(evt);
            }
        });
        getContentPane().add(framebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pushy_bg_1.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
     String title = titleTextField.getText();
     String body = bodyTextArea.getText();
     if(deviceList.getSelectedIndex() == -1){
         JOptionPane.showMessageDialog(null,"Please select a device!");
     }else{
        int i = deviceList.getSelectedIndex();
        String iden = PushBulletService.getDeviceID(i);
        String name = PushBulletService.getDeviceName(i);

        PushBulletService.sendMessage(iden, title, body, name);
     }
 
    }//GEN-LAST:event_sendButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        titleTextField.setText(null);
        bodyTextArea.setText(null);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void resetButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseEntered
        resetButton.setRolloverIcon(resetText);
    }//GEN-LAST:event_resetButtonMouseEntered

    private void sendButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseEntered
        sendButton.setRolloverIcon(sendText);
    }//GEN-LAST:event_sendButtonMouseEntered

    private void framebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framebarMouseDragged
        X = evt.getXOnScreen();
        Y = evt.getYOnScreen();
        this.setLocation(X-cX, Y-cY);
    }//GEN-LAST:event_framebarMouseDragged

    private void framebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framebarMousePressed
        cX = evt.getX();
        cY = evt.getY();
    }//GEN-LAST:event_framebarMousePressed

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void closeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseEntered
        closeLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_closeLabelMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bodyLabel;
    private javax.swing.JTextArea bodyTextArea;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JList<String> deviceList;
    private javax.swing.JLabel framebar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel sendToLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
